### ISSUE TITLE
Write state functionality

### ISSUE THREAD

**Issue by dselans** [9corp/9volt#14]
State is going to be updated by checks.

State is used for being able to provide the API with information about what the member/cluster is doing.

Idea is that the state should be written out (periodically) by each member to etcd; API then accesses and exposes data from etcd.

**Comment by dselans** [comment]
Wooooooo! 🔥

**Comment by jessedearing** [comment]
I think I may need to figure out how to give checks unique identifiers. They can be based on an arbitrary name or something crazy like a UUID.

**Comment by dselans** [comment]
I went with uuid's for tagging inbound alert messages; seems to get the job done; using `github.com/satori/go.uuid` - already vendored.

**Comment by dselans** [comment]
Ignore my last comment. Checks have a name, a base64 encoded string that is used for instantiating the check. There should be no need to add any other identifiers.

**Comment by jessedearing** [comment]
Where's the base64 string getting passed that would define the check?

**Comment by dselans** [comment]
Really simple initial implementation - just dump state information on an interval. This may need to be further expanded in the future to be a bit more sophisticated.

Addressed in #64
