### ISSUE TITLE
Write basic checks

### ISSUE THREAD

**Issue by dselans** [9corp/9volt#15]
@jessedearing has already done a good chunk of it, but I don't remember where we left off.

Creating ticket to just track progress.

Checks that should be written out of the gate:

1. Basic TCP check (w/ banner check?)
2. HTTP Status code check
3. HTTP content + status code check (maybe this goes into the main http check?)
4. ICMP ... (this would be nice, but requires root privs...)

Bonus:

1. MySQL check

**Comment by jessedearing** [comment]
So far I have a HTTP and a generic exec that evaluates non-zero exit codes for failure. I need to still create a TCP check with banner check parameters.

I was thinking for MySQL we could just use the exec check and call the mysql command line. The thought being that we don't have to include mysql libraries in 9volt for something that is less likely to be utilized.

**Comment by dselans** [comment]
This ticket has been separated into multiple tickets instead - easier to manage.
