### ISSUE TITLE
UI not working: ensure you pass 'X-Access-Token' in header

### ISSUE THREAD

**Issue by hsmade** [9corp/9volt#154]
I cloned the repo, did a docker-compose up -d and opened http://localhost:8080/ui/Cluster as per https://github.com/9corp/9volt/blob/master/docs/DOCKER.md It seems that this needs to be one of the other ports, like 8081. But these give me:

    {"message":"No access token found; ensure you pass 'X-Access-Token' in header","status":"error"}

**Comment by dselans** [comment]
Thanks for the report. You're right - the readme references the wrong port (8080 vs 8081) and seems like there's something up with tokens. If there are none passed, the token middleware shouldn't get called, but in this case it does.

I'll investigate this soon.

**Comment by dselans** [comment]
Hey there - this should be working once more. It's ultimately not a "proper" fix - as in, the issue will surface once more if access tokens are used - but it should be good enough to get started. The UI is getting overhauled in the near future.
