### ISSUE TITLE
DNS check

### ISSUE THREAD

**Issue by dselans** [9corp/9volt#28]
Write a DNS server check:

- Check that given DNS server is able to resolve something
- Maybe check that it's able to resolve something in a given timeframe?

**Comment by relistan** [comment]
I've started on a basic DNS check. Should be able to check:

1. That a particular DNS server can resolve a record
2. That the result is within a time limit
3. That the resulting record is the correct type
4. That the contents of the record are correct

**Comment by dselans** [comment]
Awesome! Accept the project invite so I can assign the issue to you!

**Comment by relistan** [comment]
Accepted!

Code is WIP here: https://github.com/9corp/9volt/tree/relistan/dns-check
