### ISSUE TITLE
Multiple alerter problem

### ISSUE THREAD

**Issue by dselans** [9corp/9volt#33]
The fact that we allow multiple alerters for both critical and warning means that if someone configures "slack" and "slack" for both warning and critical, you will get two "resolve" notifications whenever a check resolves.

In other words:

WarningAlerter: ["slack", "email"]
CriticalAlerter: ["pagerduty"]

Would work fine - when the check resolves, it will send a resolve to pagerduty, a resolve to slack and to email.

If however we configured:

WarningAlerter: ["slack", "email"]
CriticalAlerter: ["slack", "pagerduty"]

You will get two similar notifications in Slack about the resolve.

It's not horrible, but annoying. I can't yet think of a way to get around this case without tearing down the ability to have multiple alerters...

**Comment by relistan** [comment]
On resolution, de-dupe the alerters by name, and send one to each?

**Comment by dselans** [comment]
@relistan don't think that's possible (right now) - everything starts from the basemonitor - it sees that something exceeded a certain threshold and it constructs an alert message that it sends to the alerter component; the alerter component is basically just an executor at that point and is not aware of the configuration of the check or anything, so there's no chance for dedup. It could hold a temporary state maybe based on the source of the message? Dunno.

Let's chat after you've had a chance to look it over.

**Comment by jessedearing** [comment]
I've been thinking about this a bit too. I think you could use a finite state machine in the monitor for the alert. I think the use of a channel to send messages to the alerter might just be artificially constraining when you could use an observer-like pattern to initiate the alert from the monitor.

**Comment by dselans** [comment]
@jessedearing Yep, that's doable, just need to agree on what route we're taking. Something to keep in mind though - the 'dupe problem' is the only thing that is a 'fault' with the simple monitor -> alerter channel send. If the dupe thing wasn't an issue - this would suffice.

If we introduce some sort of a state machine into the base monitor, it'll increase complexity, so it'd be nice to see some other benefit besides dedup? Just a thought.

**Comment by jessedearing** [comment]
@dselans The complexity of the base monitor is exactly something that a FSM would solve. De-dupe seems like it would be full of edge cases and potentially error prone (I.e. multiple slack notifications). Also de-dupe would not let us create an alerting scheme where I get notified about critical alerts, but I don't want them to resolve.

**Comment by dselans** [comment]
Discussed this with @jessedearing in slack - everything makes sense. @jessedearing will take on refactoring the basemonitor to support easier extension of functionality (and as a result, allow for alert dedup).

**Comment by dselans** [comment]
This was resolved by @jessedearing
