### ISSUE TITLE
Push container image to a registery

### ISSUE THREAD

**Issue by jonDowdle** [9corp/9volt#7]
Once the image has been built, utilize CI system to push the container to a Docker registry. 

See: [Info on TravisCI and Docker](https://docs.travis-ci.com/user/docker/)

**Comment by dselans** [comment]
Using this issue to also take care of fixing/finishing all of the Docker related bits (such as optionally using env vars for 9volt startup).

**Comment by dselans** [comment]
A lot of this was completed/cleaned up in #97 ; still need to push actual images to dockerhub.

**Comment by dselans** [comment]
Official image pushed to dockerhub.
