### ISSUE TITLE
API/UI authentication?

### ISSUE THREAD

**Issue by dselans** [9corp/9volt#86]
Something to keep in mind - what do we do about authentication? Do we leave that to something else - let folks put an nginx reverse proxy in front of 9volt that handles auth via whatever method they want? Or do we handle it ourselves?

Do we need token auth on the API?

**Comment by caledhwa** [comment]
This is tough. However, it could be done. One of the approaches I've seen was done in Rancher where you could point at any OAuth provider (in that case one of the easiest ways was to use Github's OAuth). The troublesome part is if someone is running this on an isolated machine, they will likely want to point at their own auth method. We can discuss.

**Comment by dselans** [comment]
Jeff Hubbard implemented auth (token based) for the API. Closing this for now; we can address the UI issue in a new ticket.
