### ISSUE TITLE
Improve memberid generation

### ISSUE THREAD

**Issue by dselans** [9corp/9volt#99]
MemberID is currently generated off of the `listen address`. This is problematic since by default 9volt will bind to `0.0.0.0:8080` and will cause multiple members to have the same memberid.

Update to use mac address or something else that's unique.

Hrm, could this be a uuid?

**Comment by dselans** [comment]
Welp, looks like I was wrong. It's already utilizing `hostname + listenaddress` as the seed for generating the memberid. Should be good enough (?).

We could update this to use a mac address, but then we get into the territory of deciding which interface to use yada yada. 

Re: generating a random id on start doesn't make much sense as it will be impossible to tell who's who from logs at that point.

Closing.

**Comment by relistan** [comment]
Not sure if it's better or not, but Sidecar uses [this code](https://github.com/newrelic/sidecar/blob/master/addresses.go) which is heavily modified from Memberlist to find a unique IP.

**Comment by dselans** [comment]
I think that would be an improvement, but it doesn't seem like it's absolutely necessary. Docker spins up new containers with the hostname set to the container ID, this alleviates the non-unique memberid issue I thought we would start seeing.

For bare metal machines - hostnames *should* be different... hopefully?
